// <auto-generated />
namespace ERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class posstock_add3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(posstock_add3));
        
        string IMigrationMetadata.Id
        {
            get { return "201804141540498_posstock_add-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
